export const harvestEscrowAbi = [
  {
    type: "function",
    name: "createListing",
    stateMutability: "nonpayable",
    inputs: [
      { name: "cropType", type: "string" },
      { name: "weightKg", type: "uint256" },
      { name: "priceWei", type: "uint256" },
      { name: "photoHash", type: "bytes32" },
      { name: "photoURI", type: "string" },
    ],
    outputs: [{ name: "listingId", type: "uint256" }],
  },
  {
    type: "function",
    name: "fundEscrow",
    stateMutability: "payable",
    inputs: [{ name: "listingId", type: "uint256" }],
    outputs: [],
  },
  {
    type: "function",
    name: "markShipped",
    stateMutability: "nonpayable",
    inputs: [{ name: "listingId", type: "uint256" }],
    outputs: [],
  },
  {
    type: "function",
    name: "confirmReceipt",
    stateMutability: "nonpayable",
    inputs: [{ name: "listingId", type: "uint256" }],
    outputs: [],
  },
  {
    type: "function",
    name: "claimAfterTimeout",
    stateMutability: "nonpayable",
    inputs: [{ name: "listingId", type: "uint256" }],
    outputs: [],
  },
  {
    type: "function",
    name: "resolveDispute",
    stateMutability: "nonpayable",
    inputs: [
      { name: "listingId", type: "uint256" },
      { name: "releaseToFarmer", type: "bool" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "getListing",
    stateMutability: "view",
    inputs: [{ name: "listingId", type: "uint256" }],
    outputs: [
      {
        name: "",
        type: "tuple",
        components: [
          { name: "listingId", type: "uint256" },
          { name: "farmer", type: "address" },
          { name: "buyer", type: "address" },
          { name: "cropType", type: "string" },
          { name: "weightKg", type: "uint256" },
          { name: "priceWei", type: "uint256" },
          { name: "photoHash", type: "bytes32" },
          { name: "photoURI", type: "string" },
          { name: "grade", type: "string" },
          { name: "gradeReasonURI", type: "string" },
          { name: "gradeConfidence", type: "uint256" },
          { name: "deliveryVerified", type: "bool" },
          { name: "deliveryMatched", type: "bool" },
          { name: "deliveryReasonURI", type: "string" },
          { name: "deliveryConfidence", type: "uint256" },
          { name: "status", type: "uint8" },
          { name: "deliveryDeadline", type: "uint256" },
        ],
      },
    ],
  },
  {
    type: "function",
    name: "listingCount",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    type: "event",
    name: "ListingCreated",
    inputs: [
      { name: "listingId", type: "uint256", indexed: true },
      { name: "farmer", type: "address", indexed: true },
      { name: "cropType", type: "string", indexed: false },
      { name: "weightKg", type: "uint256", indexed: false },
      { name: "priceWei", type: "uint256", indexed: false },
      { name: "photoHash", type: "bytes32", indexed: false },
      { name: "photoURI", type: "string", indexed: false },
    ],
  },
  {
    type: "event",
    name: "GradePosted",
    inputs: [
      { name: "listingId", type: "uint256", indexed: true },
      { name: "grade", type: "string", indexed: false },
      { name: "confidence", type: "uint256", indexed: false },
      { name: "reasonURI", type: "string", indexed: false },
    ],
  },
  {
    type: "event",
    name: "EscrowFunded",
    inputs: [
      { name: "listingId", type: "uint256", indexed: true },
      { name: "buyer", type: "address", indexed: true },
      { name: "amount", type: "uint256", indexed: false },
    ],
  },
  {
    type: "event",
    name: "ShipmentMarked",
    inputs: [
      { name: "listingId", type: "uint256", indexed: true },
      { name: "deliveryDeadline", type: "uint256", indexed: false },
    ],
  },
  {
    type: "event",
    name: "DeliveryVerified",
    inputs: [
      { name: "listingId", type: "uint256", indexed: true },
      { name: "matched", type: "bool", indexed: false },
      { name: "confidence", type: "uint256", indexed: false },
      { name: "reasonURI", type: "string", indexed: false },
    ],
  },
  {
    type: "event",
    name: "ReceiptConfirmed",
    inputs: [
      { name: "listingId", type: "uint256", indexed: true },
      { name: "farmer", type: "address", indexed: true },
      { name: "amount", type: "uint256", indexed: false },
    ],
  },
  {
    type: "event",
    name: "TimeoutClaimed",
    inputs: [
      { name: "listingId", type: "uint256", indexed: true },
      { name: "farmer", type: "address", indexed: true },
      { name: "amount", type: "uint256", indexed: false },
    ],
  },
  {
    type: "event",
    name: "DisputeResolved",
    inputs: [
      { name: "listingId", type: "uint256", indexed: true },
      { name: "releaseToFarmer", type: "bool", indexed: false },
      { name: "amount", type: "uint256", indexed: false },
    ],
  },
];
